checking database connection at startup

diff --git a/finance-entrypoint b/finance-entrypoint
--- a/finance-entrypoint
+++ b/finance-entrypoint
@@ -3,7 +3,51 @@
 # (C) 2012-2018 Stefan Schallenberg
 # 
 # Execute automatic tasks for finance
+
+
+
 aqb=/usr/bin/aqbanking-cli
+fnt=/usr/local/bin/fntxt2sql
+datadir=~
+
+if [ -z "$MYSQL_HOST" ] ; then
+	printf "Variable MYSQL_HOST needs to be set.\n"
+	exit 1
+elif [ -z "$MYSQL_DATABASE" ] ; then
+	printf "Variable MYSQL_DATABASE needs to be set.\n"
+	exit 1
+elif [ -z "$MYSQL_USER" ] ; then
+	printf "Variable MYSQL_USER needs to be set.\n"
+	exit 1
+elif [ -z "$MYSQL_PASSWORD" ] ; then
+	printf "Variable MYSQL_PASSWORD needs to be set.\n"
+	exit 1
+fi
+
+dbexist=$(mysql -h $MYSQL_HOST -u $MYSQL_USER \
+	--password=$MYSQL_PASSWORD $MYSQL_DATABASE -N <<-"EOF"
+	SELECT COUNT(*) 
+		FROM information_schema.tables
+		WHERE table_schema="$MYSQL_DATABASE" AND table_name="fn_entry";
+		EOF
+		)
+if [ "$?" != "0" ] ; then 
+	printf "Error connecting to datatabase %s on %s (User %s PW %s)\n" \
+		"$MYSQL_HOST" "$MYSQL_HOST" "$MYSQL_USER" "$MYSQL_PASSWORD"
+	exit 1
+fi
+
+if [ "$dbexist" == "0" ] ; then
+	printf "database %s is empty, will create tables etc.\n" "$MYSQL_DATABASE"
+	set -x
+	$fnt -cre
+fi
+
+printf "Work in progress - exiting now with Error.\n"
+
+# End for now
+exit 1
+
 
 # Call profile since CRON does not do it.
 #. ~/.profile
